# Generated by Django 3.1.11 on 2021-05-16 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField()),
                ('client_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='KeyMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=150)),
                ('public_key', models.CharField(max_length=1000)),
                ('private_key', models.CharField(max_length=1000)),
                ('key_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apis.client')),
            ],
        ),
    ]
