# Generated by Django 3.1.11 on 2021-05-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keymapping',
            name='id',
        ),
        migrations.RemoveField(
            model_name='keymapping',
            name='key_id',
        ),
        migrations.AddField(
            model_name='keymapping',
            name='client_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
